### ISSUE TITLE
TEST - Logical Compare missing

### ISSUE THREAD

**Issue by cheery** [google/CPU-instructions#2]
I've been using the output from this project lately and this came up. TEST seems to be missing in the pbtxt output entirely.

It has not done this for anything else in this project, only this one is missing in between of SYSRET and TZCNT.

That's the bug. But also I got something to say about the rest of the project. At the best the output I've gotten from it is like this:

```
instructions {
  description: "Move r32 to r/m32."
  vendor_syntax {
    mnemonic: "MOV"
    operands {
      encoding: MODRM_RM_ENCODING
      name: "r/m32"
      usage: USAGE_WRITE
    }
    operands {
      encoding: MODRM_REG_ENCODING
      name: "r32"
      usage: USAGE_READ
    }
  }
  available_in_64_bit: true
  legacy_instruction: true
  encoding_scheme: "MR"
  raw_encoding_specification: "89 /r"
  group_id: "MOV-Move"
}
```

Overall it's enough for assembling and disassembling with this thing. But not enough for simulating the architecture or calculating costs for optimization.

It also doesn't provide way to differentiate between near and far return.

I've been happy to the results despite that. It's way much nicer to browse than the large PDF files.

Manual I used as input was: "Intel® 64 and IA-32 Architectures
Software Developer’s Manual", Order Number: 325383-060US, September 2016

**Comment by legrosbuffle** [comment]
Thanks for the report, we understand what's going on and we're working on a fix.

WRT costs & simulation, we are soon going to release code that populates the [ItineraryProto](https://github.com/google/CPU-instructions/blob/master/cpu_instructions/proto/instructions.proto) message for each instruction.

In the longer term we intend to release code that simulates the timing of a sequence of instructions based on this data.

**Comment by cheery** [comment]
I confirm the fix worked. I'm getting the "TEST" now. 

```
instructions {
  description: "AND imm8 with AL; set SF, ZF, PF according to result."
  vendor_syntax {
    mnemonic: "TEST"
    operands {
      addressing_mode: DIRECT_ADDRESSING
      encoding: IMPLICIT_ENCODING
      value_size_bits: 8
      name: "AL"
      usage: USAGE_WRITE
    }
    operands {
      addressing_mode: NO_ADDRESSING
      encoding: IMMEDIATE_VALUE_ENCODING
      value_size_bits: 8
      name: "imm8"
      usage: USAGE_READ
    }
  }
  available_in_64_bit: true
  legacy_instruction: true
  encoding_scheme: "I"
  raw_encoding_specification: "A8 ib"
  x86_encoding_specification {
    opcode: 168
    legacy_prefixes {
    }
    immediate_value_bytes: 1
  }
  group_id: "TEST-Logical Compare"
}
```

Also it seems like I got "x86_encoding_specification" there as well now.

It looks like I lost some instruction specs like "AAM" or "AAA", but then I used a different manual this time because I accidentally removed the one I had with the git clean command.

Combined Volumes: 1, 2A, 2B, 2C, 2D, 3A, 3B, 3C, 3D and 4, Order Number: 325462-062US, March 2017

**Comment by gchatelet** [comment]
Thanks for letting us know. Can you please open a different bug and assign it to me? I'll work on a fix meanwhile.

**Comment by cheery** [comment]
@gchatelet I appear to have no rights to assign you, but I created a new issue nevertheless, with more details.
